---
name: Vault - Secrets Engines - SSH - Configure CA
command: |-
  vault write {{mount}}/config/ca generate_signing_key=true
tags:
  - vault
description: Configure a CA for the SSH secrets engine
arguments:
  - name: mount
    description: The name of the secrets engine mount
    default_value: ssh
author: Chris van Meer
author_url: https://chrisvanmeer.nl
shells: []
