---
name: Vault - Secrets Engines - Azure - Configuration
command: |-
  vault write {{mount}}/config \
    subscription_id={{subscription_id}} \
    tenant_id={{tenant_id}} \
    client_id={{client_id}} \
    client_secret={{client_secret}}
tags:
  - vault
  - azure
description: Write the Vault configuration of the Azure Secrets Engine
arguments:
  - name: mount
    description: Mount path of the Azure Secrets Engine
    default_value: azure
  - name: subscription_id
    description: Subscription ID
    default_value: 00000000-0000-0000-0000-000000000000
  - name: tenant_id
    description: Tenant ID
    default_value: 00000000-0000-0000-0000-000000000000
  - name: client_id
    description: Service Principal ID (Client ID)
    default_value: 00000000-0000-0000-0000-000000000000
  - name: client_secret
    description: Password (Client Secret)
    default_value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
author: Chris van Meer
author_url: https://chrisvanmeer.nl
shells: []
